spring:
  activemq:
    broker-url: 'tcp://49.235.202.56:61616'
    user: admin
    password: admin

  jms:
    pub-sub-domain: true # false queue true topic subscribe

# queue name
demo_queue: demo_queue
demo_topic: demo_topic
